# Navigation Settings
menu:
  首页: / || fas fa-home
  留言板: /message/ || fas fa-comments
  照片墙: /photos/ || fas fa-images
  音乐: /music/ || fas fa-music

# Navigation bar logo image
logo:
  display_title: true
  display_post_title: true
  fixed: false

# Comments System
comments:
  use: twikoo
  text: true
  lazyload: false
  count: false
  card_post_count: false

# Twikoo
twikoo:
  envId: https://twikoo-server-beta.vercel.app
  region:
  visitor: false
  option:

# =====公告，缩进2空格！！=====
card_announcement:
  enable: true
  content: 欢迎来到26届回忆录✨右上角可以进入留言板

# 侧边栏作者卡片
aside:
  card_author:
    enable: true
    avatar:
      img: /img/avatar.jpg
      effect: false
    name: 这是我画的仑中顾外拟人
    description: ''
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/22lyrical

# 背景图和音乐播放器
inject:
  head:
    - |
      <style>
        /* PC端 */
        body {
          background: url(/img/blzxnwl.jpg) center center/cover no-repeat fixed !important;
        }
        #page-header {
          background-color: rgba(0, 80, 60, 0.75) !important;
        }
        #page-header::before {
          background: transparent !important;
        }

        /* 手机端：修改垂直位置，优先保留图片中间内容，取消fixed防挤压 */
        @media (max-width: 768px) {
          body {
            background-attachment: scroll !important;
            background-position: center 30% !important;
          }
        }
      </style>